const XLSX = require('xlsx');

// 正向关键词数据
const keywordsData = [
  // 英文关键词
  { Keyword: 'sports streaming api', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 2.50 },
  { Keyword: 'live sports streaming api', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 2.50 },
  { Keyword: 'sports video api provider', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 3.00 },
  { Keyword: 'sports streaming api pricing', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 3.50 },
  { Keyword: 'sports streaming api enterprise', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 4.00 },
  { Keyword: 'sports streaming api integration', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 2.80 },
  { Keyword: 'live match streaming api', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 2.50 },
  { Keyword: 'video streaming api for sports', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Core API Keywords', 'Max CPC': 2.00 },
  { Keyword: 'sports streaming solution for apps', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Developer Solutions', 'Max CPC': 3.00 },
  { Keyword: 'sports streaming service for developers', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Developer Solutions', 'Max CPC': 3.20 },
  { Keyword: 'enterprise sports streaming', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Enterprise Solutions', 'Max CPC': 4.50 },
  { Keyword: 'commercial sports streaming provider', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Enterprise Solutions', 'Max CPC': 4.00 },
  { Keyword: 'white label sports streaming', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Enterprise Solutions', 'Max CPC': 5.00 },
  { Keyword: 'sports streaming sdk', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Developer Solutions', 'Max CPC': 3.50 },
  { Keyword: 'rtmp ingest provider', 'Match Type': 'Exact', Campaign: 'RTMP Campaign', 'Ad Group': 'RTMP Core Keywords', 'Max CPC': 3.00 },
  { Keyword: 'rtmp push service', 'Match Type': 'Exact', Campaign: 'RTMP Campaign', 'Ad Group': 'RTMP Core Keywords', 'Max CPC': 3.20 },
  { Keyword: 'rtmp streaming vendor', 'Match Type': 'Phrase', Campaign: 'RTMP Campaign', 'Ad Group': 'RTMP Core Keywords', 'Max CPC': 2.80 },
  { Keyword: 'rtmp streaming enterprise', 'Match Type': 'Phrase', Campaign: 'RTMP Campaign', 'Ad Group': 'RTMP Enterprise', 'Max CPC': 4.20 },
  { Keyword: 'rtmp to hls transcoding', 'Match Type': 'Exact', Campaign: 'RTMP Campaign', 'Ad Group': 'RTMP Tech Keywords', 'Max CPC': 3.50 },
  { Keyword: 'hls live stream provider', 'Match Type': 'Exact', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Core Keywords', 'Max CPC': 2.80 },
  { Keyword: 'm3u8 live stream provider', 'Match Type': 'Exact', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Core Keywords', 'Max CPC': 3.00 },
  { Keyword: 'sports m3u8 provider', 'Match Type': 'Exact', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Sports Keywords', 'Max CPC': 3.50 },
  { Keyword: 'hls streaming api sports', 'Match Type': 'Phrase', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Sports Keywords', 'Max CPC': 2.50 },
  { Keyword: 'live stream links provider', 'Match Type': 'Phrase', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Core Keywords', 'Max CPC': 2.30 },
  { Keyword: 'sports live links api', 'Match Type': 'Exact', Campaign: 'HLS Campaign', 'Ad Group': 'HLS Sports Keywords', 'Max CPC': 3.20 },
  { Keyword: 'low latency sports streaming', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Performance Keywords', 'Max CPC': 3.80 },
  { Keyword: 'global sports streaming provider', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Performance Keywords', 'Max CPC': 3.50 },
  { Keyword: 'high availability sports streaming', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Performance Keywords', 'Max CPC': 4.00 },
  { Keyword: 'sports streaming api trial', 'Match Type': 'Exact', Campaign: 'Sports API Campaign', 'Ad Group': 'Trial Keywords', 'Max CPC': 4.50 },
  { Keyword: 'sports streaming api free trial', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Trial Keywords', 'Max CPC': 4.20 },
  { Keyword: 'sports streaming provider pricing', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Pricing Keywords', 'Max CPC': 4.80 },
  { Keyword: 'sports streaming enterprise pricing', 'Match Type': 'Phrase', Campaign: 'Sports API Campaign', 'Ad Group': 'Pricing Keywords', 'Max CPC': 5.20 },
  { Keyword: 'football live stream provider b2b', 'Match Type': 'Phrase', Campaign: 'Sports Categories Campaign', 'Ad Group': 'Football B2B', 'Max CPC': 3.20 },
  { Keyword: 'basketball live stream provider b2b', 'Match Type': 'Phrase', Campaign: 'Sports Categories Campaign', 'Ad Group': 'Basketball B2B', 'Max CPC': 3.00 },
  { Keyword: 'tennis live stream provider b2b', 'Match Type': 'Phrase', Campaign: 'Sports Categories Campaign', 'Ad Group': 'Tennis B2B', 'Max CPC': 2.80 },
  { Keyword: 'esports live stream provider b2b', 'Match Type': 'Phrase', Campaign: 'Sports Categories Campaign', 'Ad Group': 'Esports B2B', 'Max CPC': 3.50 },
  { Keyword: 'SportStreamHD', 'Match Type': 'Exact', Campaign: 'Brand Campaign', 'Ad Group': 'Brand Core', 'Max CPC': 1.00 },
  { Keyword: 'SportStreamHD api', 'Match Type': 'Exact', Campaign: 'Brand Campaign', 'Ad Group': 'Brand Core', 'Max CPC': 1.50 },
  { Keyword: 'SportStreamHD pricing', 'Match Type': 'Exact', Campaign: 'Brand Campaign', 'Ad Group': 'Brand Core', 'Max CPC': 2.00 },
  
  // 中文关键词
  { Keyword: '体育直播流 api', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '核心API关键词', 'Max CPC': 3.00 },
  { Keyword: '体育直播 接口 对接', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '核心API关键词', 'Max CPC': 3.20 },
  { Keyword: '体育视频 api 接入', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '核心API关键词', 'Max CPC': 2.80 },
  { Keyword: '体育直播 api 服务商', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '核心API关键词', 'Max CPC': 3.50 },
  { Keyword: '体育直播 api 报价', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '报价关键词', 'Max CPC': 4.50 },
  { Keyword: '体育直播 api 企业 接入', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '企业级关键词', 'Max CPC': 4.20 },
  { Keyword: 'rtmp 推流 服务', 'Match Type': 'Exact', Campaign: '中文RTMP Campaign', 'Ad Group': 'RTMP核心词', 'Max CPC': 3.20 },
  { Keyword: 'rtmp 推流 供应商', 'Match Type': 'Exact', Campaign: '中文RTMP Campaign', 'Ad Group': 'RTMP核心词', 'Max CPC': 3.50 },
  { Keyword: 'rtmp 转 hls 转码', 'Match Type': 'Phrase', Campaign: '中文RTMP Campaign', 'Ad Group': 'RTMP技术词', 'Max CPC': 3.80 },
  { Keyword: 'hls 直播 服务商', 'Match Type': 'Exact', Campaign: '中文HLS Campaign', 'Ad Group': 'HLS核心词', 'Max CPC': 3.00 },
  { Keyword: 'm3u8 直播 链接 供应商', 'Match Type': 'Phrase', Campaign: '中文HLS Campaign', 'Ad Group': 'HLS核心词', 'Max CPC': 3.20 },
  { Keyword: '体育 hls 直播 接入', 'Match Type': 'Phrase', Campaign: '中文HLS Campaign', 'Ad Group': 'HLS体育词', 'Max CPC': 2.80 },
  { Keyword: '体育直播 b端 解决方案', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '企业级关键词', 'Max CPC': 4.80 },
  { Keyword: '体育直播 企业级 服务', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '企业级关键词', 'Max CPC': 4.50 },
  { Keyword: '体育直播 技术 服务商', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '企业级关键词', 'Max CPC': 4.00 },
  { Keyword: '体育直播 白标 方案', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '企业级关键词', 'Max CPC': 5.50 },
  { Keyword: '体育直播 sdk', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '开发者关键词', 'Max CPC': 3.50 },
  { Keyword: '低延迟 体育直播 流', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '性能关键词', 'Max CPC': 4.00 },
  { Keyword: '全球 覆盖 体育直播', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '性能关键词', 'Max CPC': 3.80 },
  { Keyword: '稳定 体育直播 流媒体', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '性能关键词', 'Max CPC': 3.50 },
  { Keyword: '体育直播 api 试用', 'Match Type': 'Exact', Campaign: '中文API Campaign', 'Ad Group': '试用关键词', 'Max CPC': 4.80 },
  { Keyword: '体育直播 api 免费 试用', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '试用关键词', 'Max CPC': 4.50 },
  { Keyword: '体育直播 流 价格', 'Match Type': 'Phrase', Campaign: '中文API Campaign', 'Ad Group': '报价关键词', 'Max CPC': 4.20 },
  { Keyword: '足球 直播 流 供应商', 'Match Type': 'Phrase', Campaign: '中文体育分类 Campaign', 'Ad Group': '足球B2B', 'Max CPC': 3.20 },
  { Keyword: '篮球 直播 流 供应商', 'Match Type': 'Phrase', Campaign: '中文体育分类 Campaign', 'Ad Group': '篮球B2B', 'Max CPC': 3.00 },
  { Keyword: '电竞 直播 流 供应商', 'Match Type': 'Phrase', Campaign: '中文体育分类 Campaign', 'Ad Group': '电竞B2B', 'Max CPC': 3.50 },
  { Keyword: '网球 直播 流 供应商', 'Match Type': 'Phrase', Campaign: '中文体育分类 Campaign', 'Ad Group': '网球B2B', 'Max CPC': 2.80 },
  { Keyword: 'SportStreamHD 接入', 'Match Type': 'Exact', Campaign: '中文品牌 Campaign', 'Ad Group': '品牌核心', 'Max CPC': 1.50 },
  { Keyword: 'SportStreamHD 报价', 'Match Type': 'Exact', Campaign: '中文品牌 Campaign', 'Ad Group': '品牌核心', 'Max CPC': 2.00 }
];

// 否定关键词数据
const negativeKeywordsData = [
  // 中文C端词
  { 'Negative Keyword': '免费看', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '免费直播', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '免费观看', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '直播源', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '直播吧', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '在线直播', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '高清直播', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '现场直播', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '看比赛', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '今日直播', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '在线观看', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '视频回放', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '录像', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '集锦', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '下载', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'app', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '电视台', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '频道', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'CCTV5', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '咪咕', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '腾讯体育', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '爱奇艺体育', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'bilibili', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '优酷', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '爱奇艺', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '免费', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '破解', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '盗版', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '资源', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '种子', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '磁力', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'BT下载', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '迅雷', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '网盘', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '百度云', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '阿里云盘', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  
  // 英文C端词
  { 'Negative Keyword': 'free stream', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'watch live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'free live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'hd live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'reddit stream', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'ace stream', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'kodi', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'iptv', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'download', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'full match', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'highlights', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'replay', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'torrent', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'youtube', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'twitch', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'channel', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'schedule today', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'live tv', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'watch online', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'streaming free', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'live stream free', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'cracked', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'pirate', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'illegal', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'bootleg', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'unauthorized', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'hack', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'bypass', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'unblock', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'vpn', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'proxy', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'mirror', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'alternative', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'reddit', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'discord', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'telegram channel', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'facebook live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'instagram live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'tiktok live', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  
  // 知名流媒体平台
  { 'Negative Keyword': 'buffstream', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'streameast', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'crackstreams', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'sportsurge', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'firstrowsports', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'live365', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'atdhe', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'vipbox', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'wiziwig', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'rojadirecta', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'livescore', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'flashscore', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '365scores', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'espn', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'fox sports', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'sky sports', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'bbc sport', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'cbs sports', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'nbc sports', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'dazn', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'amazon prime', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'netflix', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'hulu', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'disney plus', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'paramount plus', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'peacock', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'apple tv', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'roku', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'fire tv', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'chromecast', 'Match Type': 'Exact', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'smart tv', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'android tv', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'ios app', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'android app', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': 'mobile app', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  
  // 个人用户相关
  { 'Negative Keyword': '个人用户', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '家庭用户', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '个人观看', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '家庭观看', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '消费者', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '终端用户', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '个人订阅', 'Match Type': 'Broad', Campaign: 'All Campaigns' },
  { 'Negative Keyword': '家庭套餐', 'Match Type': 'Broad', Campaign: 'All Campaigns' }
];

// 创建工作簿
const workbook = XLSX.utils.book_new();

// 创建关键词工作表
const keywordsSheet = XLSX.utils.json_to_sheet(keywordsData);
XLSX.utils.book_append_sheet(workbook, keywordsSheet, 'Keywords');

// 创建否定关键词工作表
const negativeKeywordsSheet = XLSX.utils.json_to_sheet(negativeKeywordsData);
XLSX.utils.book_append_sheet(workbook, negativeKeywordsSheet, 'Negative Keywords');

// 保存文件
XLSX.writeFile(workbook, 'ads/google_ads_keywords.xlsx');

console.log('✅ Excel文件已生成: ads/google_ads_keywords.xlsx');
console.log(`📊 正向关键词: ${keywordsData.length} 个`);
console.log(`🚫 否定关键词: ${negativeKeywordsData.length} 个`);
